# Generated by Django 5.0.6 on 2024-07-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('⭐⭐⭐', '⭐⭐⭐'), ('⭐', '⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐')], max_length=20),
        ),
    ]
